Repository Olympus-Team/OKRs-enterprise-api, pull requests merged in 2020-09, with the labels that each got.

#321 chore: update codecov
  src/app.controller.ts
Labels: enhancement, 🚀 merge it 🚀

#322 Fix/codecov
  .github/workflows/build.yml
  package.json
Labels: bug, 🚀 merge it 🚀

#325 fix: fix view parent objective
  src/modules/objective/objective.repository.ts
Labels: 🚀 merge it 🚀

#327 fix: fix data checkin status and okrs status dashboard screen
  src/modules/checkin/checkin.repository.ts
  src/modules/objective/objective.repository.ts
Labels: 🚀 merge it 🚀
