Repository Olympus-Team/OKRs-enterprise-api, pull requests merged in 2020-07, with the labels that each got.

#66 Feature/crud measure unit
  package.json
  src/app.module.ts
  src/db/database-connetion.service.ts
  src/modules/measure-unit/__test__/measure.controller.spec.ts
  src/modules/measure-unit/__test__/measure.service.spec.ts
  src/modules/measure-unit/measure-unit.controller.ts
  src/modules/measure-unit/measure-unit.dto.ts
  src/modules/measure-unit/measure-unit.module.ts
  src/modules/measure-unit/measure-unit.repository.ts
  src/modules/measure-unit/measure-unit.service.ts
Labels: feature_request, 🚀 merge it 🚀

#67 Feature/crud evaluation criteria
  src/app.module.ts
  src/constants/app.enums.ts
  src/constants/app.exeption.ts
  src/db/database-connetion.service.ts
  src/modules/criteria/__test__/criteria.controller.spec.ts
  src/modules/criteria/__test__/criteria.service.spec.ts
  src/modules/criteria/criteria.controller.ts
  src/modules/criteria/criteria.dto.ts
  src/modules/criteria/criteria.module.ts
  src/modules/criteria/criteria.repository.ts
  src/modules/criteria/criteria.service.ts
  src/modules/measure-unit/measure-unit.controller.ts
  src/modules/measure-unit/measure-unit.repository.ts
  src/modules/measure-unit/measure-unit.service.ts
Labels: 🚀 merge it 🚀

#68 feat: add pagination service to app
  .eslintrc.js
  src/app.module.ts
  src/constants/app.enums.ts
  src/constants/app.magic-number.ts
  src/modules/criteria/__test__/criteria.service.spec.ts
  src/modules/criteria/criteria.controller.ts
  src/modules/criteria/criteria.module.ts
  src/modules/criteria/criteria.service.ts
  src/modules/evaluation-criteria/__test__/evaluationCriteria.controller.spec.ts
  src/modules/evaluation-criteria/__test__/evaluationCriteria.service.spec.ts
  src/modules/evaluation-criteria/evaluation-criteria.controller.ts
  src/modules/evaluation-criteria/evaluation-criteria.dto.ts
  src/modules/evaluation-criteria/evaluation-criteria.module.ts
  src/modules/evaluation-criteria/evaluation-criteria.repository.ts
  src/modules/evaluation-criteria/evaluation-criteria.service.ts
  src/modules/measure-unit/__test__/measureUnit.controller.spec.ts
  src/modules/measure-unit/__test__/measureUnit.service.spec.ts
  src/modules/measure-unit/measure-unit.controller.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.service.ts
  yarn.lock
Labels: feature_request

#103 fix: bug register (#102)
  src/modules/auth/auth.dto.ts
  src/modules/auth/auth.service.ts
Labels: bug
